(* Wirth Extended Backus-Naur Form of Proc
http://www.cs.man.ac.uk/~pjj/bnf/ebnf.html *)

(* Any other characters to extend language *)
  OtherLetter = ∅.
   OtherDigit = ∅.

(* Base language characters *)
  LatinLetter = "A" | "B" | ... | "Z" | "a" | "b" | ... | "z".
 DecimalDigit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9".

(* Proc letters and digits *)
       Letter = LatinLetter | OtherLetter | OtherDigit.
        Digit = DecimalDigit | LatinLetter.

(* Language strings *)
    Character = Letter | Digit.
         Char = "'" {Char} "'".
       String = "\"" {Char} "\"".

(* Proc *)
       Global = MethodDeclaration | MethodCall { Global }.
   Identifier = Letter { Letter | Digit }.
