' https://plantuml.com/sitemap-language-specification

@startuml Proc

/'
    owners feed pets, pets please owners (association)
    a tail is a part of both dogs and cats (aggregation / composition)
    a cat is a kind of pet (inheritance / generalization)
    specific pet is a cat (specialization)
    Extension?
'/

class NeutralContainer

class Stream << Token >>
{
    Платформозависимая
    реализация реального
    носителя информации
    вычислителя
}

interface Reader
{
    Читает состояния
    из потока
}

interface Writer
{
    Пишет состояния
    в поток
}

Stream --|> Reader
Stream --|> Writer

class Utf8 << Token >>
{
    Поток UTF-8
    формата юникода
}

Utf8 o-- Reader
Utf8 o-- Writer

interface UnicodeReader
{
    Читает коды символов
    юникода из потока
}

interface UnicodeWriter
{
    Пишет коды символов
    юникода в поток
}

Utf8 --|> UnicodeReader
Utf8 --|> UnicodeWriter

class SourceToken << Token >>
{
    SourceToken может быть
    целесообразен, т.к.
    текстовые языки похожи
}

UnicodeReader --o SourceToken
UnicodeWriter --o SourceToken

class JavaScriptToken << Token >>
{
}

UnicodeReader --o JavaScriptToken
UnicodeWriter --o JavaScriptToken

class ProcToken << Token >>
{
}

UnicodeReader --o ProcToken
UnicodeWriter --o ProcToken

class Amd64Token << Token >>
{
}

Reader --o Amd64Token
Writer --o Amd64Token

class ArmToken << Token >>
{
}

Reader --o ArmToken
Writer --o ArmToken

class DnaToken << Token >>
{
}

Reader --o DnaToken
Writer --o DnaToken

interface StateToken << Token >>
{
    Не целесообразен,
    т.к. уникален
}

Reader --o StateToken
Writer --o StateToken

class SymbolTable
{
}

SourceToken o-- SymbolTable
JavaScriptToken o-- SymbolTable
ProcToken o-- SymbolTable
Amd64Token o-- SymbolTable
ArmToken o-- SymbolTable
DnaToken o-- SymbolTable
StateToken o-- SymbolTable

class JavaScript << Syntax >>
{
}

class Proc << Syntax >>
{
}

class Amd64 << Syntax >>
{
}

class Arm << Syntax >>
{
}

class Dna << Syntax >>
{
}

SymbolTable --o JavaScript
SymbolTable --o Proc
SymbolTable --o Amd64
SymbolTable --o Arm
SymbolTable --o Dna

JavaScriptToken --o JavaScript
'SourceToken --o JavaScript
ProcToken --o Proc
'SourceToken --o Proc
Amd64Token --o Amd64
ArmToken --o Arm
DnaToken --o Dna

class Statement << AST >>
{
}

JavaScript --o Statement
Proc --o Statement
Amd64 --o Statement
Arm --o Statement
Dna --o Statement

@enduml
